parameters:
    youshido.uploadable.namer: Youshido\UploadableBundle\Tools\Namer\Md5HashNamer
    youshido.uploadable.base_upload_dir: %kernel.root_dir%/../web

services:
    youshido.uploadable.reader:
        class: Youshido\UploadableBundle\Annotations\Reader\UploadableReader

    youshido.uploadable.namer:
        class: %youshido.uploadable.namer%

    youshido.uploadable.file_manager:
        class: Youshido\UploadableBundle\Manager\FileManager
        arguments: ['@youshido.uploadable.namer']
        calls:
            - [ setBaseUploadDir, [%youshido.uploadable.base_upload_dir%] ]
            - [ setContainer, ['@service_container']]

    youshido.uploadable.enity_manager:
        class: Youshido\UploadableBundle\Manager\EntityManager
        arguments: ['@youshido.uploadable.reader', '@youshido.uploadable.file_manager']
        calls:
            - [ setContainer, ['@service_container']]

    youshido.uploadable.listener:
        class: Youshido\UploadableBundle\Listener\UploadableListener
        arguments: ['@youshido.uploadable.reader', '@youshido.uploadable.file_manager' ]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    youshido.uploadable.form.type.youshido_file:
        class: Youshido\UploadableBundle\Type\FileType
        arguments: [ '@youshido.uploadable.reader', '@validator' ]
        tags:
          - { name: form.type, alias: youshido_file }
